// Mocks generated by Mockito 5.4.6 from annotations
// in bloomsafe/test/widget/features/aqi_monitoring/presentation/screens/aqi_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:bloomsafe/core/error/error_processor.dart' as _i6;
import 'package:bloomsafe/features/aqi_monitoring/data/models/aqi_data.dart'
    as _i3;
import 'package:bloomsafe/features/aqi_monitoring/domain/repositories/aqi_repository.dart'
    as _i2;
import 'package:bloomsafe/features/aqi_monitoring/presentation/state/aqi_provider.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAQIRepository_0 extends _i1.SmartFake implements _i2.AQIRepository {
  _FakeAQIRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAQIData_1 extends _i1.SmartFake implements _i3.AQIData {
  _FakeAQIData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AQIProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAQIProvider extends _i1.Mock implements _i4.AQIProvider {
  MockAQIProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AQIRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAQIRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AQIRepository);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isFromCache =>
      (super.noSuchMethod(Invocation.getter(#isFromCache), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchData(String? zipcode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchData, [zipcode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> retry() =>
      (super.noSuchMethod(
            Invocation.method(#retry, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
    Invocation.method(#clearData, []),
    returnValueForMissingStub: null,
  );

  @override
  void setError(
    String? errorMessage, {
    _i6.ErrorCategory? category = _i6.ErrorCategory.unknown,
  }) => super.noSuchMethod(
    Invocation.method(#setError, [errorMessage], {#category: category}),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AQIRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAQIRepository extends _i1.Mock implements _i2.AQIRepository {
  MockAQIRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.AQIData> getAQIByZipcode(String? zipcode) =>
      (super.noSuchMethod(
            Invocation.method(#getAQIByZipcode, [zipcode]),
            returnValue: _i5.Future<_i3.AQIData>.value(
              _FakeAQIData_1(
                this,
                Invocation.method(#getAQIByZipcode, [zipcode]),
              ),
            ),
          )
          as _i5.Future<_i3.AQIData>);

  @override
  _i5.Future<bool> hasDataForZipCode(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#hasDataForZipCode, [zipCode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AQIData?> getCachedDataForZipCode(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedDataForZipCode, [zipCode]),
            returnValue: _i5.Future<_i3.AQIData?>.value(),
          )
          as _i5.Future<_i3.AQIData?>);

  @override
  _i5.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#isFromCache, []),
            returnValue: false,
          )
          as bool);

  @override
  Duration getCacheAge(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheAge, [zipCode]),
            returnValue: _FakeDuration_2(
              this,
              Invocation.method(#getCacheAge, [zipCode]),
            ),
          )
          as Duration);
}
