// Mocks generated by Mockito 5.4.6 from annotations
// in bloomsafe/test/widget/features/aqi_monitoring/presentation/widgets/zipcode_input_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:bloomsafe/core/error/error_processor.dart' as _i5;
import 'package:bloomsafe/core/services/connectivity_service.dart' as _i7;
import 'package:bloomsafe/features/aqi_monitoring/domain/repositories/aqi_repository.dart'
    as _i2;
import 'package:bloomsafe/features/aqi_monitoring/presentation/state/aqi_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAQIRepository_0 extends _i1.SmartFake implements _i2.AQIRepository {
  _FakeAQIRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AQIProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAQIProvider extends _i1.Mock implements _i3.AQIProvider {
  MockAQIProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AQIRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAQIRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AQIRepository);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isFromCache =>
      (super.noSuchMethod(Invocation.getter(#isFromCache), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> fetchData(String? zipcode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchData, [zipcode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> retry() =>
      (super.noSuchMethod(
            Invocation.method(#retry, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
    Invocation.method(#clearData, []),
    returnValueForMissingStub: null,
  );

  @override
  void setError(
    String? errorMessage, {
    _i5.ErrorCategory? category = _i5.ErrorCategory.unknown,
  }) => super.noSuchMethod(
    Invocation.method(#setError, [errorMessage], {#category: category}),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i7.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i7.ConnectivityStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i4.Stream<_i7.ConnectivityStatus>.empty(),
          )
          as _i4.Stream<_i7.ConnectivityStatus>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i7.ConnectivityStatus getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i7.ConnectivityStatus.wifi,
          )
          as _i7.ConnectivityStatus);

  @override
  bool isOnline() =>
      (super.noSuchMethod(Invocation.method(#isOnline, []), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> hasInternetConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternetConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasInternetConnectionWithTimeout() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternetConnectionWithTimeout, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void setStatus(_i7.ConnectivityStatus? status) => super.noSuchMethod(
    Invocation.method(#setStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
