// Mocks generated by Mockito 5.4.6 from annotations
// in bloomsafe/test/unit/features/aqi_monitoring/presentation/state/aqi_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloomsafe/core/services/analytics_service.dart' as _i9;
import 'package:bloomsafe/features/aqi_monitoring/data/models/aqi_category.dart'
    as _i4;
import 'package:bloomsafe/features/aqi_monitoring/data/models/aqi_data.dart'
    as _i2;
import 'package:bloomsafe/features/aqi_monitoring/data/models/pollutant_data.dart'
    as _i7;
import 'package:bloomsafe/features/aqi_monitoring/domain/repositories/aqi_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:timezone/timezone.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAQIData_0 extends _i1.SmartFake implements _i2.AQIData {
  _FakeAQIData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTZDateTime_2 extends _i1.SmartFake implements _i3.TZDateTime {
  _FakeTZDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAQICategory_4 extends _i1.SmartFake implements _i4.AQICategory {
  _FakeAQICategory_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AQIRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAQIRepository extends _i1.Mock implements _i5.AQIRepository {
  MockAQIRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AQIData> getAQIByZipcode(String? zipcode) =>
      (super.noSuchMethod(
            Invocation.method(#getAQIByZipcode, [zipcode]),
            returnValue: _i6.Future<_i2.AQIData>.value(
              _FakeAQIData_0(
                this,
                Invocation.method(#getAQIByZipcode, [zipcode]),
              ),
            ),
          )
          as _i6.Future<_i2.AQIData>);

  @override
  _i6.Future<bool> hasDataForZipCode(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#hasDataForZipCode, [zipCode]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AQIData?> getCachedDataForZipCode(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedDataForZipCode, [zipCode]),
            returnValue: _i6.Future<_i2.AQIData?>.value(),
          )
          as _i6.Future<_i2.AQIData?>);

  @override
  _i6.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#isFromCache, []),
            returnValue: false,
          )
          as bool);

  @override
  Duration getCacheAge(String? zipCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheAge, [zipCode]),
            returnValue: _FakeDuration_1(
              this,
              Invocation.method(#getCacheAge, [zipCode]),
            ),
          )
          as Duration);
}

/// A class which mocks [AQIData].
///
/// See the documentation for Mockito's code generation for more information.
class MockAQIData extends _i1.Mock implements _i2.AQIData {
  MockAQIData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.PollutantData> get pollutants =>
      (super.noSuchMethod(
            Invocation.getter(#pollutants),
            returnValue: <_i7.PollutantData>[],
          )
          as List<_i7.PollutantData>);

  @override
  String get dateObserved =>
      (super.noSuchMethod(
            Invocation.getter(#dateObserved),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#dateObserved),
            ),
          )
          as String);

  @override
  int get hourObserved =>
      (super.noSuchMethod(Invocation.getter(#hourObserved), returnValue: 0)
          as int);

  @override
  _i3.TZDateTime get observationTime =>
      (super.noSuchMethod(
            Invocation.getter(#observationTime),
            returnValue: _FakeTZDateTime_2(
              this,
              Invocation.getter(#observationTime),
            ),
          )
          as _i3.TZDateTime);

  @override
  _i3.TZDateTime get validUntil =>
      (super.noSuchMethod(
            Invocation.getter(#validUntil),
            returnValue: _FakeTZDateTime_2(
              this,
              Invocation.getter(#validUntil),
            ),
          )
          as _i3.TZDateTime);

  @override
  DateTime get observationDate =>
      (super.noSuchMethod(
            Invocation.getter(#observationDate),
            returnValue: _FakeDateTime_3(
              this,
              Invocation.getter(#observationDate),
            ),
          )
          as DateTime);

  @override
  set observationTime(_i3.TZDateTime? _observationTime) => super.noSuchMethod(
    Invocation.setter(#observationTime, _observationTime),
    returnValueForMissingStub: null,
  );

  @override
  set validUntil(_i3.TZDateTime? _validUntil) => super.noSuchMethod(
    Invocation.setter(#validUntil, _validUntil),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool isExpired() =>
      (super.noSuchMethod(Invocation.method(#isExpired, []), returnValue: false)
          as bool);

  @override
  bool isFresh() =>
      (super.noSuchMethod(Invocation.method(#isFresh, []), returnValue: false)
          as bool);

  @override
  void logValidityInfo() => super.noSuchMethod(
    Invocation.method(#logValidityInfo, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PollutantData].
///
/// See the documentation for Mockito's code generation for more information.
class MockPollutantData extends _i1.Mock implements _i7.PollutantData {
  MockPollutantData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get parameterName =>
      (super.noSuchMethod(
            Invocation.getter(#parameterName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#parameterName),
            ),
          )
          as String);

  @override
  int get aqi =>
      (super.noSuchMethod(Invocation.getter(#aqi), returnValue: 0) as int);

  @override
  _i4.AQICategory get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _FakeAQICategory_4(this, Invocation.getter(#category)),
          )
          as _i4.AQICategory);

  @override
  bool get isPM25 =>
      (super.noSuchMethod(Invocation.getter(#isPM25), returnValue: false)
          as bool);

  @override
  bool get isO3 =>
      (super.noSuchMethod(Invocation.getter(#isO3), returnValue: false)
          as bool);

  @override
  bool get isPM10 =>
      (super.noSuchMethod(Invocation.getter(#isPM10), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [AnalyticsServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsServiceInterface extends _i1.Mock
    implements _i9.AnalyticsServiceInterface {
  MockAnalyticsServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logEvent(
    String? eventName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logScreenView(String? screenName, {String? screenClass}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logScreenView,
              [screenName],
              {#screenClass: screenClass},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAnalyticsCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAnalyticsCollectionEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendTestEvent() =>
      (super.noSuchMethod(
            Invocation.method(#sendTestEvent, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAqiSearch(String? zipcode, bool? success) =>
      (super.noSuchMethod(
            Invocation.method(#logAqiSearch, [zipcode, success]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAqiResultViewed(
    String? severityLevel,
    double? pm25Value, {
    String? reportingArea,
    String? stateCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logAqiResultViewed,
              [severityLevel, pm25Value],
              {#reportingArea: reportingArea, #stateCode: stateCode},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logGuideContentViewed(
    String? contentId,
    String? contentName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logGuideContentViewed, [contentId, contentName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLearnArticleViewed(
    String? articleId,
    String? articleCategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logLearnArticleViewed, [
              articleId,
              articleCategory,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logRecommendationViewed(
    String? severityLevel,
    String? recommendationType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logRecommendationViewed, [
              severityLevel,
              recommendationType,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logContentShared(String? contentType, String? shareMethod) =>
      (super.noSuchMethod(
            Invocation.method(#logContentShared, [contentType, shareMethod]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logFeedbackSubmitted(String? feedbackType) =>
      (super.noSuchMethod(
            Invocation.method(#logFeedbackSubmitted, [feedbackType]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSettingsChanged(String? settingName, String? newValue) =>
      (super.noSuchMethod(
            Invocation.method(#logSettingsChanged, [settingName, newValue]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logError(String? errorType, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#logError, [errorType, message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setReproductiveHealthInterest(String? interest) =>
      (super.noSuchMethod(
            Invocation.method(#setReproductiveHealthInterest, [interest]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAqiRegion(String? region) =>
      (super.noSuchMethod(
            Invocation.method(#setAqiRegion, [region]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAppUsageFrequency(String? frequency) =>
      (super.noSuchMethod(
            Invocation.method(#setAppUsageFrequency, [frequency]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setEducationSectionsCompleted(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setEducationSectionsCompleted, [count]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
